#!/usr/bin/env python3
"""Generate a static, read-only HTML catalog page from registry/index.json.

Usage: generate_catalog_html.py

This is the "Web portal" from .trellis/spec/architecture/04-audience-distribution-channels.md
Phase 1 form: no server, no DB, no auth - just a static page rendered from the same
index generate_index.py already produces. It only shows *published* (approved)
skills and their install commands - actual submission/upload always goes through
review_pipeline.py (a raw upload widget here would bypass the review gate, which
defeats the point - see .trellis/spec/security/05-solo-operator-playbook.md).
For the pipeline/audit trail itself, see generate_audit_html.py -> audit.html.

Content scope (2026-07-02 direction from user): OpenCode is the primary install
target, OpenClaw is the named future direction - Claude Code marketplace.json is
still generated by generate_index.py for anyone who wants it, but is intentionally
NOT surfaced on this card UI anymore.

Visual style: see scripts/_style.py (tokens extracted from skillhub.club's actual
compiled CSS). 2026-07-02 second pass: first version matched the color/border
tokens but still read as "thin documentation," not a product - added a colored
cover band + icon per card (deterministic from skill name, no real cover images
available) and a real copy-to-clipboard install button instead of a bare code
block, since that's what was actually making it feel unfinished.
"""
import hashlib
import html
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _style import CSS, topbar  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "registry" / "index.json"
OUT = ROOT / "registry" / "catalog.html"

RISK_COLOR = {"low": "var(--green)", "medium": "var(--amber)", "high": "var(--red)", "unknown": "var(--muted)"}
SOURCE_LABEL = {
    "collected-external": "外部采集",
    "colleague-submitted": "同事投稿",
    "self-authored": "自己编写",
}

# No real cover images exist for these skills - pick a deterministic icon +
# gradient pair per skill name so cards have visual weight/variety instead of
# being flat text blocks. Not meant to be "correct" categorization, just texture.
COVER_ICONS = ["✨", "⚡", "🧩", "🎨", "🔧", "📝", "🤖", "🔎", "📈", "🛠️"]
COVER_GRADIENTS = [
    "linear-gradient(135deg,#fde68a,#fca5a5)",
    "linear-gradient(135deg,#a7f3d0,#93c5fd)",
    "linear-gradient(135deg,#fbcfe8,#c4b5fd)",
    "linear-gradient(135deg,#fed7aa,#fca5a5)",
    "linear-gradient(135deg,#bae6fd,#a7f3d0)",
    "linear-gradient(135deg,#ddd6fe,#fbcfe8)",
]


def cover_for(name: str):
    h = int(hashlib.sha256(name.encode()).hexdigest(), 16)
    return COVER_ICONS[h % len(COVER_ICONS)], COVER_GRADIENTS[h % len(COVER_GRADIENTS)]


PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="utf-8">
<title>SKILL-HUB — Catalog</title>
<style>
{css}
  .hero {{ padding: 8px 0 28px; }}
  .hero h1 {{ font-size: 2.1rem; margin: 4px 0 8px; }}
  .grid {{ display: grid; grid-template-columns: 1fr; gap: 22px; }}
  @media (min-width: 720px) {{ .grid {{ grid-template-columns: 1fr 1fr; }} }}
  .card {{
    border: 2px solid var(--border); background: #fff;
    display: flex; flex-direction: column; overflow: hidden;
    transition: transform .15s ease, box-shadow .15s ease;
  }}
  .card:hover {{ transform: translateY(-3px); box-shadow: 5px 5px 0 0 rgba(0,0,0,1); }}
  .cover {{
    height: 96px; display: flex; align-items: center; justify-content: center;
    font-size: 2.6rem; border-bottom: 2px solid var(--border);
  }}
  .card-head {{ padding: 12px 18px 0; display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }}
  .badge {{
    display: inline-block; font-size: 0.66rem; padding: 4px 10px; font-weight: 700;
    border: 1.5px solid var(--border); background: #fff; color: var(--ink); text-transform: uppercase;
    letter-spacing: 0.03em; border-radius: 999px;
  }}
  .badge.risk {{ color: white; border-color: transparent; }}
  .card-body {{ padding: 12px 18px 18px; flex: 1; }}
  .card-body h2 {{ margin: 6px 0 8px 0; font-size: 1.22rem; font-weight: 800; letter-spacing: -0.01em; }}
  .desc {{ color: #333; line-height: 1.6; font-size: 0.9rem; }}
  .card-foot {{ border-top: 2px solid var(--border); background: var(--secondary); padding: 14px 18px; }}
  .install-row {{ display: flex; align-items: center; gap: 10px; }}
  .install-btn {{
    flex: 1; display: flex; align-items: center; justify-content: center; gap: 8px;
    background: var(--green); color: #fff; border: 2px solid var(--border);
    font-weight: 700; font-size: 0.82rem; text-transform: uppercase; letter-spacing: 0.03em;
    padding: 10px 14px; cursor: pointer; transition: background .12s ease;
  }}
  .install-btn:hover {{ background: var(--green-hover); }}
  .install-btn.copied {{ background: var(--ink); }}
  .install-cmd {{
    display: none; margin-top: 10px; background: #fff; border: 1.5px solid var(--border); padding: 10px 12px;
    font-family: ui-monospace, "SF Mono", monospace; font-size: 0.74rem; overflow-x: auto; white-space: pre; line-height: 1.5;
  }}
  .install-cmd.shown {{ display: block; }}
  .roadmap {{ font-size: 0.7rem; color: var(--muted); margin-top: 10px; }}
</style>
</head>
<body>
{topbar}
<div class="hero">
  <h1>发现内网 Skill</h1>
  <p class="meta">面向 <strong>OpenCode</strong> 的内网 skill 目录（未来会扩展到 <strong>OpenClaw</strong> 生态）— 只展示 <code>approved</code> 状态的 skill；安装口令随点随拿，不需要登录。发布/上传走 <code>review_pipeline.py</code>，不走网页，这里是浏览 + 下载专用页。</p>
  <div class="stats">
    <div class="stat"><div class="n">{approved_count}</div><div class="label">Skills Approved</div></div>
    <div class="stat"><div class="n">{low_risk_count}</div><div class="label">Low Risk</div></div>
  </div>
  <input id="search" type="text" placeholder="搜索 skill 名称或描述…" oninput="filterCards(this.value)">
</div>
<div class="grid" id="grid">
{skills_html}
</div>
<script>
function filterCards(q) {{
  q = q.toLowerCase();
  document.querySelectorAll('.card').forEach(c => {{
    c.style.display = c.dataset.search.includes(q) ? '' : 'none';
  }});
}}
function toggleInstall(btn, name) {{
  const cmdBox = document.getElementById('cmd-' + name);
  const cmd = 'bash scripts/install.sh ' + name + ' ~/.config/opencode/skills';
  cmdBox.textContent = cmd;
  cmdBox.classList.add('shown');
  navigator.clipboard?.writeText(cmd).catch(() => {{}});
  btn.textContent = '已复制到剪贴板 ✓';
  btn.classList.add('copied');
  setTimeout(() => {{ btn.textContent = '安装（OpenCode）'; btn.classList.remove('copied'); }}, 1800);
}}
</script>
</body>
</html>
"""

SKILL_TEMPLATE = """<div class="card" data-search="{search_key}">
  <div class="cover" style="background:{gradient}">{icon}</div>
  <div class="card-head">
    <span class="badge risk" style="background:{risk_color}">风险: {risk_tier}</span>
    <span class="badge">{source_label}</span>
  </div>
  <div class="card-body">
    <h2>{name}</h2>
    <p class="desc">{description}</p>
  </div>
  <div class="card-foot">
    <div class="install-row">
      <button class="install-btn" onclick="toggleInstall(this, '{name}')">安装（OpenCode）</button>
    </div>
    <div class="install-cmd" id="cmd-{name}"></div>
    <div class="roadmap">OpenClaw / ClawHub 兼容支持：待该生态成熟后跟进</div>
  </div>
</div>
"""


def main():
    if not INDEX.exists():
        print(f"error: {INDEX} not found - run generate_index.py first", file=sys.stderr)
        raise SystemExit(1)

    data = json.loads(INDEX.read_text())
    skills = data.get("skills", [])
    low_risk_count = sum(1 for s in skills if s.get("risk_tier") == "low")

    if not skills:
        skills_html = '<p class="empty">暂无 approved 的 skill。</p>'
    else:
        blocks = []
        for s in skills:
            icon, gradient = cover_for(s["name"])
            blocks.append(SKILL_TEMPLATE.format(
                name=html.escape(s["name"]),
                description=html.escape(s["description"]),
                source_label=html.escape(SOURCE_LABEL.get(s["source"], s["source"])),
                risk_tier=html.escape(s["risk_tier"]),
                risk_color=RISK_COLOR.get(s["risk_tier"], RISK_COLOR["unknown"]),
                search_key=html.escape((s["name"] + " " + s["description"]).lower()),
                icon=icon, gradient=gradient,
            ))
        skills_html = "\n".join(blocks)

    OUT.write_text(PAGE_TEMPLATE.format(
        css=CSS, topbar=topbar("catalog"), skills_html=skills_html,
        approved_count=len(skills), low_risk_count=low_risk_count,
    ))
    print(f"wrote {OUT} ({len(skills)} skills)")


if __name__ == "__main__":
    main()
